# poert chage
server:
  port: 8081



spring:
  session:
    store-type: redis
    redis:
      namespace: yoo:session

  ############################
  ## Redis Setting
  # docker Set
  # docker run -d --name security-redies-db -p 6379:6379 redis --requirepass "123"
  ############################
  data:
    redis:
      host: localhost
      port: 6379
      password: 123