services:
  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Bind custom Nginx config
    depends_on:
      - app1
      - app2
    networks:
      - my_network  # nginx를 app1과 app2와 같은 네트워크에 연결

  app1:
    image: openjdk:17
    container_name: web01
    ports:
      - "8080:8080"
    volumes:
      - ./app.jar:/app/app.jar  # Mount JAR file for app1
    command: ["java", "-jar", "/app/app.jar", "--spring.profiles.active=sub"]
    networks:
      - my_network

  app2:
    image: openjdk:17
    container_name: web02
    ports:
      - "8081:8081"
    volumes:
      - ./app.jar:/app/app.jar  # Mount JAR file for app2
    command: ["java", "-jar", "/app/app.jar", "--spring.profiles.active=sub2"]
    networks:
      - my_network

networks:
  my_network:
    driver: bridge