
services:
  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    ports:
      - "80:80"  # Nginx는 80번 포트에서 수신
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # 로드밸런싱 설정을 위한 Nginx 설정 파일