spring:
  session:
    store-type: redis
    redis:
      # Redis에 저장될 Key Prefix
      namespace: yoo:session

  ############################
  ## Redis Setting
  # docker Set
  # docker run -d --name security-redies-db -p 6379:6379 redis --requirepass "123"
  ############################
  data:
    redis:
      host: localhost
      port: 6379
      password: 123


      #yoo:session:sessions:7ac73671-e50b-4129-8847-1c987f7c6d2e
      #yoo:session:sessions:7ac73671-e50b-4129-8847-1c987f7c6d2e